export const PERMISSIONS = {
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  USER_APPROVAL: 'USER_APPROVAL',
  MARKET_VIEW: 'MARKET_VIEW',
  MARKET_EDIT: 'MARKET_EDIT',
  VIEW_INSIGHT: 'VIEW_INSIGHT',
  MODULE_MANAGEMENT: 'MODULE_MANAGEMENT',
  BRANCH_MANAGEMENT: 'BRANCH_MANAGEMENT',
  NAVIGATION_MANAGEMENT: 'NAVIGATION_MANAGEMENT',
  SYSTEM_MIGRATION: 'SYSTEM_MIGRATION',
  SYSTEM_RESTORE: 'SYSTEM_RESTORE',
  SYSTEM_DIAGNOSTICS: 'SYSTEM_DIAGNOSTICS'
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
